// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EquipControlService.proto

// Protobuf Java Version: 3.25.1
package com.grpcproject.smartfarm.EquipControlService;

public final class EquipControlServiceProto {
  private EquipControlServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EquipPowerReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpcproject.smartfarm.EquipPowerReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string equipName = 1;</code>
     * @return The equipName.
     */
    java.lang.String getEquipName();
    /**
     * <code>string equipName = 1;</code>
     * @return The bytes for equipName.
     */
    com.google.protobuf.ByteString
        getEquipNameBytes();
  }
  /**
   * Protobuf type {@code com.grpcproject.smartfarm.EquipPowerReq}
   */
  public static final class EquipPowerReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpcproject.smartfarm.EquipPowerReq)
      EquipPowerReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EquipPowerReq.newBuilder() to construct.
    private EquipPowerReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipPowerReq() {
      equipName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EquipPowerReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.Builder.class);
    }

    public static final int EQUIPNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object equipName_ = "";
    /**
     * <code>string equipName = 1;</code>
     * @return The equipName.
     */
    @java.lang.Override
    public java.lang.String getEquipName() {
      java.lang.Object ref = equipName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipName_ = s;
        return s;
      }
    }
    /**
     * <code>string equipName = 1;</code>
     * @return The bytes for equipName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEquipNameBytes() {
      java.lang.Object ref = equipName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(equipName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, equipName_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(equipName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, equipName_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq)) {
        return super.equals(obj);
      }
      com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq other = (com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq) obj;

      if (!getEquipName()
          .equals(other.getEquipName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EQUIPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getEquipName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpcproject.smartfarm.EquipPowerReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpcproject.smartfarm.EquipPowerReq)
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.Builder.class);
      }

      // Construct using com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        equipName_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerReq_descriptor;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq getDefaultInstanceForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq build() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq buildPartial() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq result = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.equipName_ = equipName_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq) {
          return mergeFrom((com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq other) {
        if (other == com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq.getDefaultInstance()) return this;
        if (!other.getEquipName().isEmpty()) {
          equipName_ = other.equipName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                equipName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object equipName_ = "";
      /**
       * <code>string equipName = 1;</code>
       * @return The equipName.
       */
      public java.lang.String getEquipName() {
        java.lang.Object ref = equipName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          equipName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string equipName = 1;</code>
       * @return The bytes for equipName.
       */
      public com.google.protobuf.ByteString
          getEquipNameBytes() {
        java.lang.Object ref = equipName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          equipName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string equipName = 1;</code>
       * @param value The equipName to set.
       * @return This builder for chaining.
       */
      public Builder setEquipName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        equipName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string equipName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipName() {
        equipName_ = getDefaultInstance().getEquipName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string equipName = 1;</code>
       * @param value The bytes for equipName to set.
       * @return This builder for chaining.
       */
      public Builder setEquipNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        equipName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpcproject.smartfarm.EquipPowerReq)
    }

    // @@protoc_insertion_point(class_scope:com.grpcproject.smartfarm.EquipPowerReq)
    private static final com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq();
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EquipPowerReq>
        PARSER = new com.google.protobuf.AbstractParser<EquipPowerReq>() {
      @java.lang.Override
      public EquipPowerReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EquipPowerReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipPowerReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EquipPowerResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpcproject.smartfarm.EquipPowerRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 equipPowerStatus = 1;</code>
     * @return The equipPowerStatus.
     */
    int getEquipPowerStatus();
  }
  /**
   * Protobuf type {@code com.grpcproject.smartfarm.EquipPowerRes}
   */
  public static final class EquipPowerRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpcproject.smartfarm.EquipPowerRes)
      EquipPowerResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EquipPowerRes.newBuilder() to construct.
    private EquipPowerRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipPowerRes() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EquipPowerRes();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.Builder.class);
    }

    public static final int EQUIPPOWERSTATUS_FIELD_NUMBER = 1;
    private int equipPowerStatus_ = 0;
    /**
     * <code>int32 equipPowerStatus = 1;</code>
     * @return The equipPowerStatus.
     */
    @java.lang.Override
    public int getEquipPowerStatus() {
      return equipPowerStatus_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (equipPowerStatus_ != 0) {
        output.writeInt32(1, equipPowerStatus_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (equipPowerStatus_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, equipPowerStatus_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes)) {
        return super.equals(obj);
      }
      com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes other = (com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes) obj;

      if (getEquipPowerStatus()
          != other.getEquipPowerStatus()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EQUIPPOWERSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getEquipPowerStatus();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpcproject.smartfarm.EquipPowerRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpcproject.smartfarm.EquipPowerRes)
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.Builder.class);
      }

      // Construct using com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        equipPowerStatus_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipPowerRes_descriptor;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes getDefaultInstanceForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes build() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes buildPartial() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes result = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.equipPowerStatus_ = equipPowerStatus_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes) {
          return mergeFrom((com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes other) {
        if (other == com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes.getDefaultInstance()) return this;
        if (other.getEquipPowerStatus() != 0) {
          setEquipPowerStatus(other.getEquipPowerStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                equipPowerStatus_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int equipPowerStatus_ ;
      /**
       * <code>int32 equipPowerStatus = 1;</code>
       * @return The equipPowerStatus.
       */
      @java.lang.Override
      public int getEquipPowerStatus() {
        return equipPowerStatus_;
      }
      /**
       * <code>int32 equipPowerStatus = 1;</code>
       * @param value The equipPowerStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEquipPowerStatus(int value) {

        equipPowerStatus_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 equipPowerStatus = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipPowerStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        equipPowerStatus_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpcproject.smartfarm.EquipPowerRes)
    }

    // @@protoc_insertion_point(class_scope:com.grpcproject.smartfarm.EquipPowerRes)
    private static final com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes();
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EquipPowerRes>
        PARSER = new com.google.protobuf.AbstractParser<EquipPowerRes>() {
      @java.lang.Override
      public EquipPowerRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EquipPowerRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipPowerRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipPowerRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EquipStatusReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpcproject.smartfarm.EquipStatusReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string equipStatusRequest = 1;</code>
     * @return The equipStatusRequest.
     */
    java.lang.String getEquipStatusRequest();
    /**
     * <code>string equipStatusRequest = 1;</code>
     * @return The bytes for equipStatusRequest.
     */
    com.google.protobuf.ByteString
        getEquipStatusRequestBytes();
  }
  /**
   * Protobuf type {@code com.grpcproject.smartfarm.EquipStatusReq}
   */
  public static final class EquipStatusReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpcproject.smartfarm.EquipStatusReq)
      EquipStatusReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EquipStatusReq.newBuilder() to construct.
    private EquipStatusReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipStatusReq() {
      equipStatusRequest_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EquipStatusReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.Builder.class);
    }

    public static final int EQUIPSTATUSREQUEST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object equipStatusRequest_ = "";
    /**
     * <code>string equipStatusRequest = 1;</code>
     * @return The equipStatusRequest.
     */
    @java.lang.Override
    public java.lang.String getEquipStatusRequest() {
      java.lang.Object ref = equipStatusRequest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipStatusRequest_ = s;
        return s;
      }
    }
    /**
     * <code>string equipStatusRequest = 1;</code>
     * @return The bytes for equipStatusRequest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEquipStatusRequestBytes() {
      java.lang.Object ref = equipStatusRequest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipStatusRequest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(equipStatusRequest_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, equipStatusRequest_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(equipStatusRequest_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, equipStatusRequest_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq)) {
        return super.equals(obj);
      }
      com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq other = (com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq) obj;

      if (!getEquipStatusRequest()
          .equals(other.getEquipStatusRequest())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EQUIPSTATUSREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getEquipStatusRequest().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpcproject.smartfarm.EquipStatusReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpcproject.smartfarm.EquipStatusReq)
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.Builder.class);
      }

      // Construct using com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        equipStatusRequest_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusReq_descriptor;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq getDefaultInstanceForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq build() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq buildPartial() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq result = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.equipStatusRequest_ = equipStatusRequest_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq) {
          return mergeFrom((com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq other) {
        if (other == com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq.getDefaultInstance()) return this;
        if (!other.getEquipStatusRequest().isEmpty()) {
          equipStatusRequest_ = other.equipStatusRequest_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                equipStatusRequest_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object equipStatusRequest_ = "";
      /**
       * <code>string equipStatusRequest = 1;</code>
       * @return The equipStatusRequest.
       */
      public java.lang.String getEquipStatusRequest() {
        java.lang.Object ref = equipStatusRequest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          equipStatusRequest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string equipStatusRequest = 1;</code>
       * @return The bytes for equipStatusRequest.
       */
      public com.google.protobuf.ByteString
          getEquipStatusRequestBytes() {
        java.lang.Object ref = equipStatusRequest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          equipStatusRequest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string equipStatusRequest = 1;</code>
       * @param value The equipStatusRequest to set.
       * @return This builder for chaining.
       */
      public Builder setEquipStatusRequest(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        equipStatusRequest_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string equipStatusRequest = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipStatusRequest() {
        equipStatusRequest_ = getDefaultInstance().getEquipStatusRequest();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string equipStatusRequest = 1;</code>
       * @param value The bytes for equipStatusRequest to set.
       * @return This builder for chaining.
       */
      public Builder setEquipStatusRequestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        equipStatusRequest_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpcproject.smartfarm.EquipStatusReq)
    }

    // @@protoc_insertion_point(class_scope:com.grpcproject.smartfarm.EquipStatusReq)
    private static final com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq();
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EquipStatusReq>
        PARSER = new com.google.protobuf.AbstractParser<EquipStatusReq>() {
      @java.lang.Override
      public EquipStatusReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EquipStatusReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipStatusReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EquipStatusResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpcproject.smartfarm.EquipStatusRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string equipName = 1;</code>
     * @return The equipName.
     */
    java.lang.String getEquipName();
    /**
     * <code>string equipName = 1;</code>
     * @return The bytes for equipName.
     */
    com.google.protobuf.ByteString
        getEquipNameBytes();

    /**
     * <code>int32 equipStatusCode = 2;</code>
     * @return The equipStatusCode.
     */
    int getEquipStatusCode();
  }
  /**
   * Protobuf type {@code com.grpcproject.smartfarm.EquipStatusRes}
   */
  public static final class EquipStatusRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpcproject.smartfarm.EquipStatusRes)
      EquipStatusResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EquipStatusRes.newBuilder() to construct.
    private EquipStatusRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipStatusRes() {
      equipName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EquipStatusRes();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.Builder.class);
    }

    public static final int EQUIPNAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object equipName_ = "";
    /**
     * <code>string equipName = 1;</code>
     * @return The equipName.
     */
    @java.lang.Override
    public java.lang.String getEquipName() {
      java.lang.Object ref = equipName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        equipName_ = s;
        return s;
      }
    }
    /**
     * <code>string equipName = 1;</code>
     * @return The bytes for equipName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEquipNameBytes() {
      java.lang.Object ref = equipName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EQUIPSTATUSCODE_FIELD_NUMBER = 2;
    private int equipStatusCode_ = 0;
    /**
     * <code>int32 equipStatusCode = 2;</code>
     * @return The equipStatusCode.
     */
    @java.lang.Override
    public int getEquipStatusCode() {
      return equipStatusCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(equipName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, equipName_);
      }
      if (equipStatusCode_ != 0) {
        output.writeInt32(2, equipStatusCode_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(equipName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, equipName_);
      }
      if (equipStatusCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, equipStatusCode_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes)) {
        return super.equals(obj);
      }
      com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes other = (com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes) obj;

      if (!getEquipName()
          .equals(other.getEquipName())) return false;
      if (getEquipStatusCode()
          != other.getEquipStatusCode()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EQUIPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getEquipName().hashCode();
      hash = (37 * hash) + EQUIPSTATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getEquipStatusCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpcproject.smartfarm.EquipStatusRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpcproject.smartfarm.EquipStatusRes)
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.class, com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.Builder.class);
      }

      // Construct using com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        equipName_ = "";
        equipStatusCode_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.internal_static_com_grpcproject_smartfarm_EquipStatusRes_descriptor;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes getDefaultInstanceForType() {
        return com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes build() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes buildPartial() {
        com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes result = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.equipName_ = equipName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.equipStatusCode_ = equipStatusCode_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes) {
          return mergeFrom((com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes other) {
        if (other == com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes.getDefaultInstance()) return this;
        if (!other.getEquipName().isEmpty()) {
          equipName_ = other.equipName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getEquipStatusCode() != 0) {
          setEquipStatusCode(other.getEquipStatusCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                equipName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                equipStatusCode_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object equipName_ = "";
      /**
       * <code>string equipName = 1;</code>
       * @return The equipName.
       */
      public java.lang.String getEquipName() {
        java.lang.Object ref = equipName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          equipName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string equipName = 1;</code>
       * @return The bytes for equipName.
       */
      public com.google.protobuf.ByteString
          getEquipNameBytes() {
        java.lang.Object ref = equipName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          equipName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string equipName = 1;</code>
       * @param value The equipName to set.
       * @return This builder for chaining.
       */
      public Builder setEquipName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        equipName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string equipName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipName() {
        equipName_ = getDefaultInstance().getEquipName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string equipName = 1;</code>
       * @param value The bytes for equipName to set.
       * @return This builder for chaining.
       */
      public Builder setEquipNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        equipName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int equipStatusCode_ ;
      /**
       * <code>int32 equipStatusCode = 2;</code>
       * @return The equipStatusCode.
       */
      @java.lang.Override
      public int getEquipStatusCode() {
        return equipStatusCode_;
      }
      /**
       * <code>int32 equipStatusCode = 2;</code>
       * @param value The equipStatusCode to set.
       * @return This builder for chaining.
       */
      public Builder setEquipStatusCode(int value) {

        equipStatusCode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 equipStatusCode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEquipStatusCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        equipStatusCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpcproject.smartfarm.EquipStatusRes)
    }

    // @@protoc_insertion_point(class_scope:com.grpcproject.smartfarm.EquipStatusRes)
    private static final com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes();
    }

    public static com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EquipStatusRes>
        PARSER = new com.google.protobuf.AbstractParser<EquipStatusRes>() {
      @java.lang.Override
      public EquipStatusRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EquipStatusRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipStatusRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcproject.smartfarm.EquipControlService.EquipControlServiceProto.EquipStatusRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcproject_smartfarm_EquipPowerReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcproject_smartfarm_EquipPowerReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcproject_smartfarm_EquipPowerRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcproject_smartfarm_EquipPowerRes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcproject_smartfarm_EquipStatusReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcproject_smartfarm_EquipStatusReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcproject_smartfarm_EquipStatusRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcproject_smartfarm_EquipStatusRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031EquipControlService.proto\022\031com.grpcpro" +
      "ject.smartfarm\"\"\n\rEquipPowerReq\022\021\n\tequip" +
      "Name\030\001 \001(\t\")\n\rEquipPowerRes\022\030\n\020equipPowe" +
      "rStatus\030\001 \001(\005\",\n\016EquipStatusReq\022\032\n\022equip" +
      "StatusRequest\030\001 \001(\t\"<\n\016EquipStatusRes\022\021\n" +
      "\tequipName\030\001 \001(\t\022\027\n\017equipStatusCode\030\002 \001(" +
      "\0052\347\001\n\023equipControlService\022i\n\021equipPowerC" +
      "ontrol\022(.com.grpcproject.smartfarm.Equip" +
      "PowerReq\032(.com.grpcproject.smartfarm.Equ" +
      "ipPowerRes(\001\022e\n\013equipStatus\022).com.grpcpr" +
      "oject.smartfarm.EquipStatusReq\032).com.grp" +
      "cproject.smartfarm.EquipStatusRes0\001BK\n-c" +
      "om.grpcproject.smartfarm.EquipControlSer" +
      "viceB\030EquipControlServiceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpcproject_smartfarm_EquipPowerReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpcproject_smartfarm_EquipPowerReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcproject_smartfarm_EquipPowerReq_descriptor,
        new java.lang.String[] { "EquipName", });
    internal_static_com_grpcproject_smartfarm_EquipPowerRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpcproject_smartfarm_EquipPowerRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcproject_smartfarm_EquipPowerRes_descriptor,
        new java.lang.String[] { "EquipPowerStatus", });
    internal_static_com_grpcproject_smartfarm_EquipStatusReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_grpcproject_smartfarm_EquipStatusReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcproject_smartfarm_EquipStatusReq_descriptor,
        new java.lang.String[] { "EquipStatusRequest", });
    internal_static_com_grpcproject_smartfarm_EquipStatusRes_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_grpcproject_smartfarm_EquipStatusRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcproject_smartfarm_EquipStatusRes_descriptor,
        new java.lang.String[] { "EquipName", "EquipStatusCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
