// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SensorDataCollectService.proto

// Protobuf Java Version: 3.25.1
package com.grpcproject.smartfarm.SensorDataCollectService;

public final class SensorDataCollectServiceProto {
  private SensorDataCollectServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SaveSensorDataReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpcproject.smartfarm.SaveSensorDataReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 soilTemp = 1;</code>
     * @return The soilTemp.
     */
    int getSoilTemp();

    /**
     * <code>int32 soilHumidity = 2;</code>
     * @return The soilHumidity.
     */
    int getSoilHumidity();
  }
  /**
   * Protobuf type {@code com.grpcproject.smartfarm.SaveSensorDataReq}
   */
  public static final class SaveSensorDataReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpcproject.smartfarm.SaveSensorDataReq)
      SaveSensorDataReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SaveSensorDataReq.newBuilder() to construct.
    private SaveSensorDataReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SaveSensorDataReq() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SaveSensorDataReq();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.class, com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.Builder.class);
    }

    public static final int SOILTEMP_FIELD_NUMBER = 1;
    private int soilTemp_ = 0;
    /**
     * <code>int32 soilTemp = 1;</code>
     * @return The soilTemp.
     */
    @java.lang.Override
    public int getSoilTemp() {
      return soilTemp_;
    }

    public static final int SOILHUMIDITY_FIELD_NUMBER = 2;
    private int soilHumidity_ = 0;
    /**
     * <code>int32 soilHumidity = 2;</code>
     * @return The soilHumidity.
     */
    @java.lang.Override
    public int getSoilHumidity() {
      return soilHumidity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (soilTemp_ != 0) {
        output.writeInt32(1, soilTemp_);
      }
      if (soilHumidity_ != 0) {
        output.writeInt32(2, soilHumidity_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (soilTemp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, soilTemp_);
      }
      if (soilHumidity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, soilHumidity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq)) {
        return super.equals(obj);
      }
      com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq other = (com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq) obj;

      if (getSoilTemp()
          != other.getSoilTemp()) return false;
      if (getSoilHumidity()
          != other.getSoilHumidity()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOILTEMP_FIELD_NUMBER;
      hash = (53 * hash) + getSoilTemp();
      hash = (37 * hash) + SOILHUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + getSoilHumidity();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpcproject.smartfarm.SaveSensorDataReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpcproject.smartfarm.SaveSensorDataReq)
        com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.class, com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.Builder.class);
      }

      // Construct using com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        soilTemp_ = 0;
        soilHumidity_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_descriptor;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq getDefaultInstanceForType() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq build() {
        com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq buildPartial() {
        com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq result = new com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.soilTemp_ = soilTemp_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.soilHumidity_ = soilHumidity_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq) {
          return mergeFrom((com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq other) {
        if (other == com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq.getDefaultInstance()) return this;
        if (other.getSoilTemp() != 0) {
          setSoilTemp(other.getSoilTemp());
        }
        if (other.getSoilHumidity() != 0) {
          setSoilHumidity(other.getSoilHumidity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                soilTemp_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                soilHumidity_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int soilTemp_ ;
      /**
       * <code>int32 soilTemp = 1;</code>
       * @return The soilTemp.
       */
      @java.lang.Override
      public int getSoilTemp() {
        return soilTemp_;
      }
      /**
       * <code>int32 soilTemp = 1;</code>
       * @param value The soilTemp to set.
       * @return This builder for chaining.
       */
      public Builder setSoilTemp(int value) {

        soilTemp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 soilTemp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoilTemp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        soilTemp_ = 0;
        onChanged();
        return this;
      }

      private int soilHumidity_ ;
      /**
       * <code>int32 soilHumidity = 2;</code>
       * @return The soilHumidity.
       */
      @java.lang.Override
      public int getSoilHumidity() {
        return soilHumidity_;
      }
      /**
       * <code>int32 soilHumidity = 2;</code>
       * @param value The soilHumidity to set.
       * @return This builder for chaining.
       */
      public Builder setSoilHumidity(int value) {

        soilHumidity_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 soilHumidity = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSoilHumidity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        soilHumidity_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpcproject.smartfarm.SaveSensorDataReq)
    }

    // @@protoc_insertion_point(class_scope:com.grpcproject.smartfarm.SaveSensorDataReq)
    private static final com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq();
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SaveSensorDataReq>
        PARSER = new com.google.protobuf.AbstractParser<SaveSensorDataReq>() {
      @java.lang.Override
      public SaveSensorDataReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SaveSensorDataReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SaveSensorDataReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.SaveSensorDataReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface saveSensorDataResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.grpcproject.smartfarm.saveSensorDataRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string response = 1;</code>
     * @return The response.
     */
    java.lang.String getResponse();
    /**
     * <code>string response = 1;</code>
     * @return The bytes for response.
     */
    com.google.protobuf.ByteString
        getResponseBytes();
  }
  /**
   * Protobuf type {@code com.grpcproject.smartfarm.saveSensorDataRes}
   */
  public static final class saveSensorDataRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.grpcproject.smartfarm.saveSensorDataRes)
      saveSensorDataResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use saveSensorDataRes.newBuilder() to construct.
    private saveSensorDataRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private saveSensorDataRes() {
      response_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new saveSensorDataRes();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_saveSensorDataRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_saveSensorDataRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.class, com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object response_ = "";
    /**
     * <code>string response = 1;</code>
     * @return The response.
     */
    @java.lang.Override
    public java.lang.String getResponse() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        response_ = s;
        return s;
      }
    }
    /**
     * <code>string response = 1;</code>
     * @return The bytes for response.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResponseBytes() {
      java.lang.Object ref = response_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        response_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(response_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, response_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(response_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes)) {
        return super.equals(obj);
      }
      com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes other = (com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes) obj;

      if (!getResponse()
          .equals(other.getResponse())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.grpcproject.smartfarm.saveSensorDataRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.grpcproject.smartfarm.saveSensorDataRes)
        com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_saveSensorDataRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_saveSensorDataRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.class, com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.Builder.class);
      }

      // Construct using com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        response_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.internal_static_com_grpcproject_smartfarm_saveSensorDataRes_descriptor;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes getDefaultInstanceForType() {
        return com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes build() {
        com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes buildPartial() {
        com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes result = new com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.response_ = response_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes) {
          return mergeFrom((com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes other) {
        if (other == com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes.getDefaultInstance()) return this;
        if (!other.getResponse().isEmpty()) {
          response_ = other.response_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                response_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object response_ = "";
      /**
       * <code>string response = 1;</code>
       * @return The response.
       */
      public java.lang.String getResponse() {
        java.lang.Object ref = response_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          response_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       * @return The bytes for response.
       */
      public com.google.protobuf.ByteString
          getResponseBytes() {
        java.lang.Object ref = response_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          response_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response = 1;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        response_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        response_ = getDefaultInstance().getResponse();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string response = 1;</code>
       * @param value The bytes for response to set.
       * @return This builder for chaining.
       */
      public Builder setResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        response_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.grpcproject.smartfarm.saveSensorDataRes)
    }

    // @@protoc_insertion_point(class_scope:com.grpcproject.smartfarm.saveSensorDataRes)
    private static final com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes();
    }

    public static com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<saveSensorDataRes>
        PARSER = new com.google.protobuf.AbstractParser<saveSensorDataRes>() {
      @java.lang.Override
      public saveSensorDataRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<saveSensorDataRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<saveSensorDataRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.grpcproject.smartfarm.SensorDataCollectService.SensorDataCollectServiceProto.saveSensorDataRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpcproject_smartfarm_saveSensorDataRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_grpcproject_smartfarm_saveSensorDataRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036SensorDataCollectService.proto\022\031com.gr" +
      "pcproject.smartfarm\";\n\021SaveSensorDataReq" +
      "\022\020\n\010soilTemp\030\001 \001(\005\022\024\n\014soilHumidity\030\002 \001(\005" +
      "\"%\n\021saveSensorDataRes\022\020\n\010response\030\001 \001(\t2" +
      "\212\001\n\030SensorDataCollectService\022n\n\016saveSens" +
      "orData\022,.com.grpcproject.smartfarm.SaveS" +
      "ensorDataReq\032,.com.grpcproject.smartfarm" +
      ".saveSensorDataRes(\001BU\n2com.grpcproject." +
      "smartfarm.SensorDataCollectServiceB\035Sens" +
      "orDataCollectServiceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcproject_smartfarm_SaveSensorDataReq_descriptor,
        new java.lang.String[] { "SoilTemp", "SoilHumidity", });
    internal_static_com_grpcproject_smartfarm_saveSensorDataRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpcproject_smartfarm_saveSensorDataRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_grpcproject_smartfarm_saveSensorDataRes_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
